---
- name: Ansible pull setup
  hosts: localhost
  tasks:
    - name: Init my personal setup
      block:
        - name: Copy zshrc file
          ansible.builtin.copy:
            src: ./zshrc
            dest: "/Users/{{ ansible_user_id }}/.zshrc"
            mode: "0644"
          when: ansible_distribution == 'MacOSX'
    - name: Copy zshrc file 2
      ansible.builtin.debug:
        msg: "hello there"
