---
- name: Ansible pull setup
  hosts: localhost
  tasks:
    - name: Init my personal setup
      block:
        - name: Copy zshrc file
          ansible.builtin.copy:
            src: ./zshrc
            dest: /Users/loyuta/.zshrc
            remote_src: true
            mode: "0644"
          when: ansible_distribution_id == 'MacOSX'
    - name: Copy zshrc file 2
      ansible.builtin.debug:
        msg: "hello there"

    # - name: Copy file
    #   ansible.builtin.template:
    #     src: zshrc.j2
    #     dest: /Users/loyuta/.zshrc
    #     mode: '0644'
