---
- name: Ansible pull setup
  hosts: localhost
  tasks:
    - name: Copy a "sudoers" file on the remote machine for editing
      ansible.builtin.copy:
        src: ./zshrc
        dest: /Users/loyuta/.zshrc
        remote_src: true
    # - name: Copy file
    #   ansible.builtin.template:
    #     src: zshrc.j2
    #     dest: /Users/loyuta/.zshrc
    #     mode: '0644'