---
- name: Ansible pull setup
  hosts: localhost
  tasks:
    - name: Init my personal setup
      block:
        - name: Copy zshrc file
          ansible.builtin.copy:
            src: ./zshrc
            dest: /Users/loyuta/.zshrc
            remote_src: true

    # - name: Copy file
    #   ansible.builtin.template:
    #     src: zshrc.j2
    #     dest: /Users/loyuta/.zshrc
    #     mode: '0644'