---
- name: Ansible pull setup
  hosts: all
  tasks:
    - name: Copy file
      ansible.builtin.template:
        src: ./zshrc.j2
        dest: /Users/{{ ansible_user_id }}/.zshrc
        mode: '0644'